/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorTaco;
import Modelo.Alimento;
import Modelo.Salsa;
import Modelo.Tortilla;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ana
 */
public final class FrmTaco extends javax.swing.JFrame {

    /**
     * Creates new form FrmTaco
     */
    ControladorTaco controladortaco = new ControladorTaco();
    DefaultTableModel dtmTortilla = new DefaultTableModel();
    DefaultTableModel dtmAlimento = new DefaultTableModel();
    DefaultTableModel dtmSalsa = new DefaultTableModel();
    //int[] arrayy = new int[2];

    public FrmTaco() {
        initComponents();
        estiloFrmTaco();
        numeroDeTacosAlmacenados();
        controladortaco.cargarComboboxss(comboTortilla, comboAlimentos, comboSalsa);
        estiloTablas(dtmTortilla, tblTortilla);
        estiloTablas(dtmAlimento, tblAlimentos);
        estiloTablas(dtmSalsa, tblSalsa);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTotalTaco = new javax.swing.JLabel();
        comboSalsa = new javax.swing.JComboBox<>();
        comboTortilla = new javax.swing.JComboBox<>();
        javax.swing.JButton btnBuscarTaco = new javax.swing.JButton();
        comboAlimentos = new javax.swing.JComboBox<>();
        btnModificar = new javax.swing.JButton();
        lbTortilla3 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lbTortilla4 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        lbTortilla6 = new javax.swing.JLabel();
        opcSimple = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAlimentos = new javax.swing.JTable();
        opcDoble = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTortilla = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSalsa = new javax.swing.JTable();
        lbTortilla10 = new javax.swing.JLabel();
        btnGuardarTaco = new javax.swing.JButton();
        txtIdTaco = new javax.swing.JTextField();
        btnTacoEconomico = new javax.swing.JButton();
        btnTacoCaro = new javax.swing.JButton();
        btnTacoPromedio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbIdTacos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        lbTotalTaco.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        lbTotalTaco.setForeground(new java.awt.Color(0, 0, 204));
        lbTotalTaco.setText("0.0");

        comboSalsa.setBackground(new java.awt.Color(205, 255, 143));
        comboSalsa.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        comboSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSalsaActionPerformed(evt);
            }
        });

        comboTortilla.setBackground(new java.awt.Color(145, 218, 155));
        comboTortilla.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        comboTortilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTortillaActionPerformed(evt);
            }
        });

        btnBuscarTaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscarTaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTacoActionPerformed(evt);
            }
        });

        comboAlimentos.setBackground(new java.awt.Color(138, 235, 176));
        comboAlimentos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        comboAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlimentosActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        lbTortilla3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbTortilla3.setText("ALIMENTOS");

        btnEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lbTortilla4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbTortilla4.setText("SALSA");

        btnLimpiar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/broom.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lbTortilla6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbTortilla6.setText("TORTILLA");

        opcSimple.setBackground(new java.awt.Color(173, 255, 139));
        opcSimple.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        opcSimple.setSelected(true);
        opcSimple.setText("Simple");
        opcSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSimpleActionPerformed(evt);
            }
        });

        tblAlimentos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        tblAlimentos.setBackground(new java.awt.Color(138, 235, 176));
        tblAlimentos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblAlimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlimentosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblAlimentos);

        opcDoble.setBackground(new java.awt.Color(173, 255, 139));
        opcDoble.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        opcDoble.setText("Doble");
        opcDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcDobleActionPerformed(evt);
            }
        });

        tblTortilla = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        tblTortilla.setBackground(new java.awt.Color(145, 218, 155));
        tblTortilla.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblTortilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTortilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTortillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTortilla);

        tblSalsa = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        tblSalsa.setBackground(new java.awt.Color(205, 255, 143));
        tblSalsa.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblSalsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblSalsa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalsaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblSalsa);

        lbTortilla10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbTortilla10.setText("Total Taco");

        btnGuardarTaco.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnGuardarTaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnGuardarTaco.setText("Guardar");
        btnGuardarTaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTacoActionPerformed(evt);
            }
        });

        txtIdTaco.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        btnTacoEconomico.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnTacoEconomico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/poor.png"))); // NOI18N
        btnTacoEconomico.setText("Taco Económico");
        btnTacoEconomico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacoEconomicoActionPerformed(evt);
            }
        });

        btnTacoCaro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnTacoCaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dollar.png"))); // NOI18N
        btnTacoCaro.setText("Taco Caro");
        btnTacoCaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacoCaroActionPerformed(evt);
            }
        });

        btnTacoPromedio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnTacoPromedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/taco.png"))); // NOI18N
        btnTacoPromedio.setText("Taco Promedio");
        btnTacoPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacoPromedioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Tacos almacenados:");

        lbIdTacos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tacos2.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-go-back-30.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbTortilla3))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(comboTortilla, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(comboAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lbTortilla4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(comboSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lbTortilla10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbTotalTaco, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(txtIdTaco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarTaco)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTacoEconomico)
                                    .addComponent(btnTacoCaro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTacoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGuardarTaco, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(opcSimple)
                        .addGap(18, 18, 18)
                        .addComponent(opcDoble))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lbTortilla6)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIdTacos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTortilla6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcSimple)
                            .addComponent(opcDoble))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboTortilla, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbIdTacos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdTaco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarTaco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(lbTortilla3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnTacoEconomico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTacoCaro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTacoPromedio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardarTaco)
                                .addGap(0, 7, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbTortilla4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTotalTaco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lbTortilla10)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSalsaActionPerformed
        if (tblSalsa.getRowCount() < 1) {
            cargarFilaDeTabla(tblSalsa, comboSalsa, dtmSalsa);
        } else {
            JOptionPane.showMessageDialog(null, "Sólo puede agregar una SALSA como MÁXIMO!!!", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_comboSalsaActionPerformed


    private void comboTortillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTortillaActionPerformed

        if (this.opcDoble.isSelected()) {
            if (tblTortilla.getRowCount() <= 1) {
                cargarFilaDeTabla(tblTortilla, comboTortilla, dtmTortilla);
            } else {
                JOptionPane.showMessageDialog(null, "Tiene seleccionada la opción DOBLE, por tanto, NO puede agregar más de 2 TORTILLAS!!!", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
            }
        } else if (opcSimple.isSelected()) {
            if (tblTortilla.getRowCount() <= 0) {
                cargarFilaDeTabla(tblTortilla, comboTortilla, dtmTortilla);
            } else {
                JOptionPane.showMessageDialog(null, "Tiene seleccionada la opción SIMPLE, por tanto, sólo puede AGREGAR 1 TORTILLA!!!", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_comboTortillaActionPerformed

    private void btnBuscarTacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTacoActionPerformed
        try {
            int idtacoBuscado = Integer.parseInt(txtIdTaco.getText());
            //controladortaco.buscarTaco(idtacoBuscado, dtmTortilla, dtmSalsa, dtmAlimento, tblTortilla, tblAlimentos, tblSalsa);
            controladortaco.buscarTaco(idtacoBuscado, dtmTortilla, dtmSalsa, dtmAlimento, tblTortilla, tblAlimentos, tblSalsa);
            //for (int i = 0; i < 2; i++) {
                //System.out.println("id array: " + arrayy[i]);
            //}

            double importe = controladortaco.obtenerImporteAlRealizarBusqueda(idtacoBuscado);
            if (importe == 0.0) {
                JOptionPane.showMessageDialog(null, "El Taco N° " + idtacoBuscado + " NO EXISTE!!!", "ERROR", JOptionPane.ERROR_MESSAGE);
                btnEliminar.setEnabled(false);
                btnModificar.setEnabled(false);
            }
            else{
               String importeS = String.valueOf(importe);
               //System.out.println("importe string:" + importeS);
               lbTotalTaco.setText(importeS);
               btnEliminar.setEnabled(true);
               btnModificar.setEnabled(true);
            }
            

            if (dtmTortilla.getRowCount() == 2) {
                this.opcSimple.setSelected(false);
                this.opcDoble.setSelected(true);
            } else {
                this.opcSimple.setSelected(true);
                this.opcDoble.setSelected(false);
            }
            

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un N° de TACO en el buscador!!", "ERROR", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_btnBuscarTacoActionPerformed
    private void limpiarTablas() {
        this.dtmTortilla.setRowCount(0);
        this.dtmAlimento.setRowCount(0);
        this.dtmSalsa.setRowCount(0);
        lbTotalTaco.setText("0.0");
        comboAlimentos.setSelectedItem("<Seleccione>");
        comboTortilla.setSelectedItem("<Seleccione>");
        comboSalsa.setSelectedItem("<Seleccione>");
        txtIdTaco.setText("");

    }

    private void cargarFilaDeTabla(JTable tabla, JComboBox combobox, DefaultTableModel dtm) {
        String Lista = (String) combobox.getSelectedItem();
        if ("<Seleccione>" != combobox.getSelectedItem()) {
            String[] Registro = Lista.split("_");
            dtm.addRow(new Object[]{Registro[0], Registro[1], Registro[2]});

            tabla.setModel(dtm);
            String total_tacos = Double.toString(Double.valueOf(lbTotalTaco.getText()) + Double.valueOf(Registro[2]));
            lbTotalTaco.setText(total_tacos);
        }
    }
    private void comboAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlimentosActionPerformed
        if (tblAlimentos.getRowCount() <= 4) {
            cargarFilaDeTabla(tblAlimentos, comboAlimentos, dtmAlimento);
        } else {
            JOptionPane.showMessageDialog(null, "Sólo puede agregar hasta 5 ALIMENTOS como MÁXIMO!!!", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_comboAlimentosActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            double importe = Double.parseDouble(lbTotalTaco.getText());

            int idtacoBuscado = Integer.parseInt(txtIdTaco.getText());

            if(controladortaco.modificarTaco(idtacoBuscado, dtmTortilla, importe, dtmAlimento, dtmSalsa)==true){
                limpiarTablas();
                btnEliminar.setEnabled(false);
                btnModificar.setEnabled(false);
            }
            
            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un N° de TACO en el buscador!!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int idtacoBuscado = Integer.parseInt(txtIdTaco.getText());
            controladortaco.eliminarTaco(idtacoBuscado);
            txtIdTaco.setText("");
            numeroDeTacosAlmacenados();
            limpiarTablas();
            btnEliminar.setEnabled(false);
            btnModificar.setEnabled(false);

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Ingrese un N° de TACO en el buscador para poder ELIMINARLO!!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarTablas();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void opcSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSimpleActionPerformed
        if (tblTortilla.getRowCount() <= 1) {
            if (this.opcSimple.isSelected()) {
                this.opcDoble.setSelected(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tiene que BORRAR una tortilla para cambiar a la OPCIÓN SIMPLE, actualmente hay 2 tortillas en la tabla...", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
            this.opcSimple.setSelected(false);
        }
    }//GEN-LAST:event_opcSimpleActionPerformed

    private void opcDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcDobleActionPerformed

        if (this.opcDoble.isSelected()) {
            this.opcSimple.setSelected(false);

        }


    }//GEN-LAST:event_opcDobleActionPerformed

    private void tblTortillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTortillaMouseClicked
        if (evt.getClickCount() == 2) { //si hace dos clicks se borra la fila de la tabla
            //String total_tacos = Double.toString(Double.valueOf(lbTotalTaco.getText()) - Double.valueOf(tblTortilla.getValueAt(tblTortilla.getSelectedRow(), 2).toString()));
            //lbTotalTaco.setText(total_tacos);
            //dtmTortilla.removeRow(tblTortilla.getSelectedRow());
            eliminarFilaDeTabla(dtmTortilla, tblTortilla);

            
            if (tblTortilla.getRowCount() == 1) {
                this.opcSimple.setSelected(true);
                this.opcDoble.setSelected(false);
            }
            
        }
    }//GEN-LAST:event_tblTortillaMouseClicked

    private void tblAlimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlimentosMouseClicked

        if (evt.getClickCount() == 2) { //si hace dos clicks se borra la fila de la tabla
            //String total_tacos = Double.toString(Double.valueOf(lbTotalTaco.getText()) - Double.valueOf(tblAlimentos.getValueAt(tblAlimentos.getSelectedRow(), 2).toString()));
            //lbTotalTaco.setText(total_tacos);
            //dtmAlimento.removeRow(tblAlimentos.getSelectedRow());
            //tblAlimentos.setModel(dtmAlimento); 
            eliminarFilaDeTabla(dtmAlimento, tblAlimentos);
        }
    }//GEN-LAST:event_tblAlimentosMouseClicked

    private void tblSalsaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalsaMouseClicked
        if (evt.getClickCount() == 2) { //si hace dos clicks se borra la fila de la tabla
            //String total_tacos = Double.toString(Double.valueOf(lbTotalTaco.getText()) - Double.valueOf(tblSalsa.getValueAt(tblSalsa.getSelectedRow(), 2).toString()));
            //lbTotalTaco.setText(total_tacos);
            //dtmSalsa.removeRow(tblSalsa.getSelectedRow());
            //tblSalsa.setModel(dtmSalsa);
            eliminarFilaDeTabla(dtmSalsa, tblSalsa);
        }
    }//GEN-LAST:event_tblSalsaMouseClicked

    private void btnGuardarTacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTacoActionPerformed
        if (tblTortilla.getRowCount() == 1 && this.opcDoble.isSelected()) {
            this.opcSimple.setSelected(true);
            this.opcDoble.setSelected(false);
        }
        double importe = Double.parseDouble(lbTotalTaco.getText());
        //System.out.println("importe: " + importe);
        controladortaco.agregarTaco(importe, dtmTortilla, dtmSalsa, dtmAlimento);
        numeroDeTacosAlmacenados();
        limpiarTablas();


    }//GEN-LAST:event_btnGuardarTacoActionPerformed

    private void btnTacoEconomicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacoEconomicoActionPerformed
        //controladortaco.llenarTablaTortillaEconomica(dtmTortilla, tblTortilla);
        dtmSalsa.setRowCount(0);
        controladortaco.generarTacoMasEconomico(dtmTortilla, tblTortilla, dtmAlimento, tblAlimentos);
        //controladortaco.llenarTablaAlimentoEconomico(dtmAlimento, tblAlimentos);

        double importe = Double.parseDouble(tblTortilla.getValueAt(0, 2).toString()) + Double.parseDouble(tblAlimentos.getValueAt(0, 2).toString());
        String val = String.valueOf(importe);
        lbTotalTaco.setText(val);
        this.opcSimple.setSelected(true);
        this.opcDoble.setSelected(false);
    }//GEN-LAST:event_btnTacoEconomicoActionPerformed

    private void btnTacoCaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacoCaroActionPerformed

        controladortaco.generarTacoMasCaro(dtmTortilla, tblTortilla, dtmAlimento, tblAlimentos, dtmSalsa, tblSalsa); //FUNCIONA SEGUIR CON LOS DEMAS

        double importe = (Double.parseDouble(tblTortilla.getValueAt(0, 2).toString()) * 2) + (Double.parseDouble(tblAlimentos.getValueAt(0, 2).toString()) * 5) + Double.parseDouble(tblSalsa.getValueAt(0, 2).toString());
        String val = String.valueOf(importe);
        lbTotalTaco.setText(val);
        this.opcSimple.setSelected(false);
        this.opcDoble.setSelected(true);

    }//GEN-LAST:event_btnTacoCaroActionPerformed

    private void btnTacoPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacoPromedioActionPerformed
        //double valorPromedioTaco = controladortaco.promedioTortillas() + controladortaco.promedioAlimentos() + controladortaco.promedioSalsas();
        //String mensaje = "Promedio de Tortillas = " + controladortaco.promedioTortillas() + "\nPromedio de Alimentos = " + controladortaco.promedioAlimentos() + "\nPromedio de Salsas = " + controladortaco.promedioSalsas() + "\nPromedio de Taco Completo = " + valorPromedioTaco;
        String mensaje = "Valor promedio de un TACO COMPLETO = " + controladortaco.obtenerValorPromedioTacoCompleto();
        JOptionPane.showMessageDialog(null, mensaje);
    }//GEN-LAST:event_btnTacoPromedioActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose(); //para que se cierre la actual:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        JOptionPane.showMessageDialog(null, "- Si desea eliminar alguno de los ingredientes agregados a las tablas,\ndebe realizar dos clicks en la fila donde se encuentra dicho ingrediente\n(tortilla, alimento o salsa)...\n- Para eliminar o editar un taco tiene que ingresar el N° de taco en el buscador");
    }//GEN-LAST:event_btnInfoActionPerformed

    private void estiloFrmTaco() {
        Color verdeAgua = new Color(173, 255, 139);
        this.getContentPane().setBackground(verdeAgua);
        this.setResizable(false);
    }

    private void numeroDeTacosAlmacenados() {
        int cantidad = controladortaco.obtenerCantidadTacosGenerados();
        //int id = controladortaco.llevoidallabel(WIDTH)
        String cantidadS = String.valueOf(cantidad);
        lbIdTacos.setText(cantidadS);
    }

    private void estiloTablas(DefaultTableModel dtm, JTable tabla) {
        String[] titulos = new String[]{"Código", "Nombre", "Precio $$$"}; //titulos de la tabla
        dtm.setColumnIdentifiers(titulos);

        tabla.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12));
        JTableHeader th;
        th = tabla.getTableHeader();
        th.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));

        tabla.setModel(dtm);

    }

    private void eliminarFilaDeTabla(DefaultTableModel dtm, JTable tabla) {
        String total_tacos = Double.toString(Double.valueOf(lbTotalTaco.getText()) - Double.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 2).toString()));
        lbTotalTaco.setText(total_tacos);
        dtm.removeRow(tabla.getSelectedRow());
        tabla.setModel(dtm);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTaco().setVisible(true);
            }
        });

        try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarTaco;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnTacoCaro;
    private javax.swing.JButton btnTacoEconomico;
    private javax.swing.JButton btnTacoPromedio;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Alimento> comboAlimentos;
    private javax.swing.JComboBox<Salsa> comboSalsa;
    private javax.swing.JComboBox<Tortilla> comboTortilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbIdTacos;
    private javax.swing.JLabel lbTortilla10;
    private javax.swing.JLabel lbTortilla3;
    private javax.swing.JLabel lbTortilla4;
    private javax.swing.JLabel lbTortilla6;
    private javax.swing.JLabel lbTotalTaco;
    private javax.swing.JRadioButton opcDoble;
    private javax.swing.JRadioButton opcSimple;
    private javax.swing.JTable tblAlimentos;
    private javax.swing.JTable tblSalsa;
    private javax.swing.JTable tblTortilla;
    private javax.swing.JTextField txtIdTaco;
    // End of variables declaration//GEN-END:variables
}
