/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ana
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setResizable(false);
        Color naranja=new Color(255, 102, 51); 
        this.getContentPane().setBackground(naranja);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAlimentos = new javax.swing.JMenuItem();
        itemSalsa = new javax.swing.JMenuItem();
        itemTortilla = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemGenerarTaco = new javax.swing.JMenuItem();
        jMenuTacoEconomico = new javax.swing.JMenuItem();
        jMenuTacoCaro = new javax.swing.JMenuItem();
        jMenuTacoPromedio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 51));

        lbTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbTitulo.setText("TACOTITO'S FOOD TRUCK");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/foodtruck.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Cargar Productos");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        itemAlimentos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        itemAlimentos.setText("Alimentos");
        itemAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlimentosActionPerformed(evt);
            }
        });
        jMenu1.add(itemAlimentos);

        itemSalsa.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        itemSalsa.setText("Salsas");
        itemSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalsaActionPerformed(evt);
            }
        });
        jMenu1.add(itemSalsa);

        itemTortilla.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        itemTortilla.setText("Tortillas");
        itemTortilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTortillaActionPerformed(evt);
            }
        });
        jMenu1.add(itemTortilla);

        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("TACOS");
        jMenu3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        itemGenerarTaco.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        itemGenerarTaco.setText("Generar taco");
        itemGenerarTaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGenerarTacoActionPerformed(evt);
            }
        });
        jMenu3.add(itemGenerarTaco);

        jMenuTacoEconomico.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jMenuTacoEconomico.setText("Taco económico");
        jMenuTacoEconomico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTacoEconomicoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuTacoEconomico);

        jMenuTacoCaro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jMenuTacoCaro.setText("Taco caro");
        jMenuTacoCaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTacoCaroActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuTacoCaro);

        jMenuTacoPromedio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jMenuTacoPromedio.setText("Promedio taco completo");
        jMenuTacoPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTacoPromedioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuTacoPromedio);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlimentosActionPerformed
        FrmAlimento frmalimento = new FrmAlimento();
        frmalimento.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_itemAlimentosActionPerformed

    private void itemSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalsaActionPerformed
        FrmSalsa frmsalsa = new FrmSalsa();
        frmsalsa.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_itemSalsaActionPerformed

    private void itemTortillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTortillaActionPerformed
        FrmTortilla frmtortilla = new FrmTortilla();
        frmtortilla.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_itemTortillaActionPerformed

    private void itemGenerarTacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGenerarTacoActionPerformed
        FrmTaco frmtaco = new FrmTaco();
        frmtaco.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_itemGenerarTacoActionPerformed

    private void jMenuTacoEconomicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTacoEconomicoActionPerformed
        JOptionPane.showMessageDialog(null, "A continuación se abrirá una ventana donde en la parte inferior hacia la derecha, encontrará un botón para ver el taco más económico...");
        FrmTaco frmtaco = new FrmTaco();
        frmtaco.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_jMenuTacoEconomicoActionPerformed

    private void jMenuTacoCaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTacoCaroActionPerformed
        JOptionPane.showMessageDialog(null, "A continuación se abrirá una ventana donde en la parte inferior hacia la derecha, encontrará un botón para ver el taco más caro...");
        FrmTaco frmtaco = new FrmTaco();
        frmtaco.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_jMenuTacoCaroActionPerformed

    private void jMenuTacoPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTacoPromedioActionPerformed
        JOptionPane.showMessageDialog(null, "A continuación se abrirá una ventana donde en la parte inferior hacia la derecha, encontrará un botón para ver el valor promedio de un taco completo...");
        FrmTaco frmtaco = new FrmTaco();
        frmtaco.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_jMenuTacoPromedioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int salida = JOptionPane.showConfirmDialog(null, "Esta seguro que desea salir??", "???", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (salida == 0) {
                JOptionPane.showMessageDialog(null, "Hasta luego!!\nTacoTito's Foodtruck");
                this.dispose();
            }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
        
        try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem itemAlimentos;
    private javax.swing.JMenuItem itemGenerarTaco;
    private javax.swing.JMenuItem itemSalsa;
    private javax.swing.JMenuItem itemTortilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuTacoCaro;
    private javax.swing.JMenuItem jMenuTacoEconomico;
    private javax.swing.JMenuItem jMenuTacoPromedio;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
